### ISSUE TITLE
Publish on rtd

### ISSUE THREAD

**Issue by hmgaudecker** [covid-19-impact-lab/liss-questionnaires#2]
Once Annica thinks this is ready to go live, it should.

I will still need to add the list of authors.

**Comment by amageh** [comment]
What does it mean to publish on readthedocs?

This is the link to the current documentation (also linked in the readme):

https://liss-covid-19-questionnaires-documentation.readthedocs.io/en/latest/

I haven't added wave 2 yet, but wave 1 is done in my opinion. Is there something else I have missed?

**Comment by hmgaudecker** [comment]
Ah, I had not realised that!!! Thanks!
